//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATB.DxfToNcConverter.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ATB.DxfToNcConverter.Resources.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug mode. Provides additional logging information while running..
        /// </summary>
        internal static string DebugModeDescription {
            get {
                return ResourceManager.GetString("DebugModeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X position at the end of program execution..
        /// </summary>
        internal static string EndXPositionDescription {
            get {
                return ResourceManager.GetString("EndXPositionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drill down moving for fasteners time in seconds..
        /// </summary>
        internal static string FastenersDrillTimeDescription {
            get {
                return ResourceManager.GetString("FastenersDrillTimeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drill down moving for holes time in seconds..
        /// </summary>
        internal static string HoleDrillTimeDescription {
            get {
                return ResourceManager.GetString("HoleDrillTimeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application creates NC files from DXF files with corresponding file names.\nEach polyline vertex in DXF file will be a drill point in creating NC program.\n\nDXF files restrictions:\n\t- Must contain at least one circle element;\n\t- Must contain only closed polylines;\n\t- All polylines must be inside the biggest circle..
        /// </summary>
        internal static string ProgramDescription {
            get {
                return ResourceManager.GetString("ProgramDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;What-if mode. It provides additional logging information while running but not performs real converting..
        /// </summary>
        internal static string WhatIfModeDescription {
            get {
                return ResourceManager.GetString("WhatIfModeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Working directory..
        /// </summary>
        internal static string WorkingDirectoryDescription {
            get {
                return ResourceManager.GetString("WorkingDirectoryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X position offset at the start of program execution..
        /// </summary>
        internal static string XPositionOffsetDescription {
            get {
                return ResourceManager.GetString("XPositionOffsetDescription", resourceCulture);
            }
        }
    }
}
