//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATB.DxfToNcConverter.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Logging_ru {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Logging_ru() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ATB.DxfToNcConverter.Resources.Logging.ru", typeof(Logging_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Самый большой круг: Идентификатор: &apos;{0}&apos;. Центр: &apos;{1}&apos;. Радиус: &apos;{2}&apos;..
        /// </summary>
        internal static string BiggestCircle {
            get {
                return ResourceManager.GetString("BiggestCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Построение NC программ....
        /// </summary>
        internal static string BuildingNcPrograms {
            get {
                return ResourceManager.GetString("BuildingNcPrograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Режим отладки активирован..
        /// </summary>
        internal static string DebugModeActivated {
            get {
                return ResourceManager.GetString("DebugModeActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Точка сверления: Отступ по X: &apos;{0}&apos;. Отступ по Y: &apos;{1}&apos;. Время сверления: &apos;{2}&apos;..
        /// </summary>
        internal static string DrillVertex {
            get {
                return ResourceManager.GetString("DrillVertex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл &apos;{0}&apos; успешно загружен..
        /// </summary>
        internal static string DxfFileLoaded {
            get {
                return ResourceManager.GetString("DxfFileLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DXF файл &apos;{0}&apos; валиден..
        /// </summary>
        internal static string DxfFileValid {
            get {
                return ResourceManager.GetString("DxfFileValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конечная точка: X: &apos;{0}&apos;, Y: &apos;{1}&apos;..
        /// </summary>
        internal static string EndPointX {
            get {
                return ResourceManager.GetString("EndPointX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Найден DXF файл: &apos;{0}&apos;.
        /// </summary>
        internal static string FoundDxfFile {
            get {
                return ResourceManager.GetString("FoundDxfFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка DXF файлов....
        /// </summary>
        internal static string LoadingDxfFiles {
            get {
                return ResourceManager.GetString("LoadingDxfFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NC файл &apos;{0}&apos; сохранен..
        /// </summary>
        internal static string NcFileSaved {
            get {
                return ResourceManager.GetString("NcFileSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В рабочей директории не найдено ни одного *.dxf файла..
        /// </summary>
        internal static string NoDxfFilesFound {
            get {
                return ResourceManager.GetString("NoDxfFilesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DXF файл &apos;{0}&apos; должен содержать хотя-бы один круг..
        /// </summary>
        internal static string NotEnoughCirclesErrorMessage {
            get {
                return ResourceManager.GetString("NotEnoughCirclesErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтение DXF файла: &apos;{0}&apos;....
        /// </summary>
        internal static string ParsingDxfFile {
            get {
                return ResourceManager.GetString("ParsingDxfFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтение  DXF файла &apos;{0}&apos; завершено..
        /// </summary>
        internal static string ParsingDxfFileComplete {
            get {
                return ResourceManager.GetString("ParsingDxfFileComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтение DXF файлов....
        /// </summary>
        internal static string ParsingDxfFiles {
            get {
                return ResourceManager.GetString("ParsingDxfFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтение полилинии: Идентификатор: &apos;{0}&apos;. Количество вершин: &apos;{1}&apos;.
        /// </summary>
        internal static string ParsingPolyline {
            get {
                return ResourceManager.GetString("ParsingPolyline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтение полилиний....
        /// </summary>
        internal static string ParsingPolylines {
            get {
                return ResourceManager.GetString("ParsingPolylines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все полилинии в DXF файле &apos;{0}&apos; должны находиться внутри самого большого круга..
        /// </summary>
        internal static string PolylineVertexIsOutsideOfTheBiggestCircleErrorMessage {
            get {
                return ResourceManager.GetString("PolylineVertexIsOutsideOfTheBiggestCircleErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нажмите любую кнопку для выхода....
        /// </summary>
        internal static string PressAnyKeyToExit {
            get {
                return ResourceManager.GetString("PressAnyKeyToExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DxfToNcConverter завершил работу..
        /// </summary>
        internal static string ProgramFinished {
            get {
                return ResourceManager.GetString("ProgramFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DxfToNcConverter начинает работу....
        /// </summary>
        internal static string ProgramStarted {
            get {
                return ResourceManager.GetString("ProgramStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранение NC программ....
        /// </summary>
        internal static string SavingNcPrograms {
            get {
                return ResourceManager.GetString("SavingNcPrograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Директория для поиска: &apos;{0}&apos;.
        /// </summary>
        internal static string SearchDirectory {
            get {
                return ResourceManager.GetString("SearchDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск DXF файлов....
        /// </summary>
        internal static string SearchingDxfFiles {
            get {
                return ResourceManager.GetString("SearchingDxfFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начальная точка: X: &apos;{0}&apos;, Y: &apos;{1}&apos;..
        /// </summary>
        internal static string StartPointX {
            get {
                return ResourceManager.GetString("StartPointX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Валидация DXF файлов....
        /// </summary>
        internal static string ValidationDxfFiles {
            get {
                return ResourceManager.GetString("ValidationDxfFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вершина в позиции &apos;{0}&apos; уже существует. Пропуск....
        /// </summary>
        internal static string VertexExists {
            get {
                return ResourceManager.GetString("VertexExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Режим Что-Если активирован..
        /// </summary>
        internal static string WhatIfModeActivated {
            get {
                return ResourceManager.GetString("WhatIfModeActivated", resourceCulture);
            }
        }
    }
}
