name: Build and publish

on:
  push:
    tags:
      - 'v*'

env:
  APP_NAME: your-app-name              # set this to your application's name
  APP_PACKAGE_PATH: './published'      # set this to the path to your app project, defaults to the repository root
  NETCORE_VERSION: '3.1.101'           # set this to the .NET Core version to use

jobs:
  build_and_publish:
    name: Build and Publish
    
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core ${{ env.NETCORE_VERSION }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.NETCORE_VERSION }}

    - name: Install dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    
    - name: Publish app for deploy
      run: dotnet publish ./ATB.DxfToNcConverter/ATB.DxfToNcConverter.csproj --configuration Release --no-build --output ${{ env.APP_PACKAGE_PATH }} /p:PublishSingleFile=true /p:CopyOutputSymbolsToPublishDirectory=false
      
    - name: Publish artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ABT.DxfToNcConverter
        path: ${{ env.APP_PACKAGE_PATH }} 
        
    - name: Get latest release
      id: get_latest_release
      uses: bruceadams/get-release@v1.2.0
    
    - name: Upload artifact to release
      uses: actions/upload-release-asset@v1.0.2
      with:
        upload_url: ${{ steps.get_latest_release.outputs.upload_url }}
        asset_path: ${{ env.APP_PACKAGE_PATH }}/ABT.DxfToNcConverter.zip
        asset_name: ABT.DxfToNcConverter.zip
        asset_content_type: application/zip
      
